version: '3.8'

services:
  exchange_scraper:
    build: .
    network_mode: host  # Set the network mode to host
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "bash install.sh --nosudo && bash install_firefox.sh --nosudo && bash run.sh"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
  
  firefox:
    image: selenium/standalone-firefox
    shm_size: 10g
    restart: unless-stopped
